feat(mm): add group list and modify the relationship of external and post
mirror-media/Lilith pull request #721
Opened 2024-04-10 06:50 UTC by gaespa007648

新增Group list，用來記錄演算法分群的結果，裡面主要有幾個欄位
1. keyword: 演算法計算某一時間內的焦點關鍵詞
2. posts: 與該關鍵詞最為相關的近期內部文章
3. externals: 與該關鍵詞最為相關的近期外部文章
hook函式僅針對keyword為空的情形進行檢查。另外，調整外部文章相關文章功能為連結週刊內部文章。

2024-04-10 07:27 UTC, erase2004 requested changes

2024-04-10 07:27 UTC, erase2004 commented on packages/mirrormedia/lists/Group.ts
> +    keyword: text({
https://keystonejs.com/docs/fields/text#title
可以設定為
```JavaScript
keyword: text({
  label: '關鍵詞',
  validation: {
    isRequired: true
  }
})
```
這樣就不用下面的 validateInput hook 了，另外，這調整會需要更新 migration SQL

2024-04-10 07:54 UTC, erase2004 approved these changes
LGTM 👏

2024-04-10 08:00 UTC, merged

2024-04-23 03:27 UTC, hcchien commented on packages/mirrormedia/lists/Post.ts
> +    from_External_relateds: relationship({
create view 跟 list view 應該是設定 hide

2024-04-23 03:27 UTC, hcchien commented on packages/mirrormedia/lists/Post.ts
> +    groups: relationship({
create view 跟 list view 應該是設定 hide